
CREATE OR ALTER PROCEDURE WSP_DISPATCH_REPORTSBL
--DECLARE
@DATE1 DATETIME,
@DATE2 DATETIME,
@SALESMANID VARCHAR(100)='%',--AGENT
@CUSTOMERACID VARCHAR(100)='%',
@MODE TINYINT ='0'--MODE 0 FOR DISPATCH ONLY ,MODE 1 FOR ALL

AS
--SELECT @DATE1='2022-05-04',@DATE2='2023-05-22'

IF @MODE=0
BEGIN

	 select LC.VOUCHERNO DISPATCHVOUCHER,SSM.NAME AGENT,OM.VCHRNO ORDERNO,OM.BSDATE ORDERMITI,TM.VCHRNO INVOICENO,TM.TRNAC,TM.BSDATE INVOICEMITI,LC.DATE DISPATCHDATE,TP.WAREHOUSE GODOWN ,RA.ACNAME from TRNMAIN TM     join LOADCHARTVOUCHERDETAIL LD ON  TM.VCHRNO=LD.REFBILL  
    
	 JOIN
	 (SELECT DISTINCT VCHRNO , WAREHOUSE FROM TRNPROD) TP ON TP.VCHRNO=TM.VCHRNO
	 LEFT JOIN
	 SALESMAN SSM ON SSM.SALESMANID=TM.SALESMANID
	LEFT JOIN  
	(SELECT DISTINCT REFBILL ,BSDATE,VCHRNO FROM RMD_ORDERMAIN WHERE VCHRNO LIKE 'SO%')OM ON OM.VCHRNO=TM.REFORDBILL
	 LEFT JOIN
	 (SELECT DISTINCT VOUCHERNO,DATE FROM LOADCHART) LC ON LC.VOUCHERNO=LD.VOUCHERNO
	 LEFT JOIN
	 (SELECT DISTINCT ACID , ACNAME FROM RMD_ACLIST WHERE ACID LIKE 'PA%') RA ON RA.ACID=TM.TRNAC

	 WHERE TM.TRNDATE BETWEEN @DATE1 AND @DATE2
	 AND ISNULL(TM.SALESMANID,'') LIKE @SALESMANID
  END

  IF @MODE=1

  BEGIN 

   select LC.VOUCHERNO DISPATCHVOUCHER,SSM.NAME AGENT,OM.VCHRNO ORDERNO,OM.BSDATE ORDERMITI,TM.VCHRNO INVOICENO,TM.TRNAC,TM.BSDATE INVOICEMITI,LC.DATE DISPATCHDATE,TP.WAREHOUSE GODOWN ,RA.ACNAME from TRNMAIN TM    LEFT join LOADCHARTVOUCHERDETAIL LD ON  TM.VCHRNO=LD.REFBILL  
    
	 JOIN
	 (SELECT DISTINCT VCHRNO , WAREHOUSE FROM TRNPROD) TP ON TP.VCHRNO=TM.VCHRNO
	 LEFT JOIN
	 SALESMAN SSM ON SSM.SALESMANID=TM.SALESMANID
	LEFT JOIN  
	(SELECT DISTINCT REFBILL ,BSDATE,VCHRNO FROM RMD_ORDERMAIN WHERE VCHRNO LIKE 'SO%')OM ON OM.VCHRNO=TM.REFORDBILL
	 LEFT JOIN
	 (SELECT DISTINCT VOUCHERNO,DATE FROM LOADCHART) LC ON LC.VOUCHERNO=LD.VOUCHERNO
	 LEFT JOIN
	 (SELECT DISTINCT ACID , ACNAME FROM RMD_ACLIST WHERE ACID LIKE 'PA%') RA ON RA.ACID=TM.TRNAC

	 WHERE TM.TRNDATE BETWEEN @DATE1 AND @DATE2
	 AND ISNULL(TM.SALESMANID,'') LIKE @SALESMANID
  END
