 
CREATE OR ALTER FUNCTION [dbo].[Fn_CalculateDepreciation] 
(
    @VALUE NUMERIC(32,2),
    @ANNUALDEPRECIATIONRATE FLOAT, 
	@INTERVAL TINYINT,--1 FOR MONTHLY, 2 FOR YEARLY
	@ASID TINYINT ,  --1 FOR STRAIGHTLINE ,2 FOR WDV
	@YPERCENTAGE NUMERIC(32,2)
)
RETURNS FLOAT
AS
BEGIN
 	DECLARE @MONTHLYDEPRECIATIONRATE FLOAT;
		DECLARE @BEGINNINGBOOKVALUE NUMERIC(32,2);
		DECLARE @DEPRECIATION NUMERIC(32,2);
		DECLARE @FINALDEPRECIATION NUMERIC(32,2)=0;
		DECLARE @DIVIDEBY INT

	 

	  
	IF(@INTERVAL=1)
	BEGIN
		SET @MONTHLYDEPRECIATIONRATE =( ( @ANNUALDEPRECIATIONRATE   )/100) / 12;
		SET @BEGINNINGBOOKVALUE = @VALUE;
		SET @DEPRECIATION = 0;
		 
	 
			SET @DEPRECIATION =  (@BEGINNINGBOOKVALUE * @MONTHLYDEPRECIATIONRATE )  ; 
			SET @FINALDEPRECIATION  =@DEPRECIATION;
		 
	 END

	 IF (@INTERVAL=2)
	 Begin
		SET @BEGINNINGBOOKVALUE=@VALUE
		SET @DEPRECIATION =  (@BEGINNINGBOOKVALUE *@ANNUALDEPRECIATIONRATE )/100
		 
		SELECT @FINALDEPRECIATION= IIF (@YPERCENTAGE=0 ,@DEPRECIATION,(@DEPRECIATION*@YPERCENTAGE)/100)

	 end


    RETURN @FINALDEPRECIATION;
END;
