 
 ALTER   PROC [dbo].[DAB_ECO_BRAND_SKU_REPORT]
--DECLARE

@DATE1 DATETIME,
@DATE2 Datetime  ,
@MCODE VARCHAR(MAX)='%',
@MCAT VARCHAR(MAX)='%',
@REPORTTYPE  VARCHAR(100)='MTD' ,
@REPMODE TINYINT= 1 ,--BEAT  0 , SALESMANWISE 1 ,STOCKIEST 2
@SALESMANID VARCHAR(MAX)='%',--SALESMANID
@STOCKIESTNAME VARCHAR(MAX)='%',--COMPANYID
@BEAT VARCHAR(MAX)='%',--ROUTECODE
@BRAND VARCHAR(MAX)='%',
@BRAND_CHECK TINYINT = 0,
@SIZE_CHECK TINYINT = 0,
@SUMMARY TINYINT =0--0 DETAIL,1 SUMMARY BRAND,2 SUMMARY SIZE
,@REPCRITERIA VARCHAR(MAX)    OUTPUT,
@REPORTNAME VARCHAR(100)     OUTPUT

AS


--SELECT @DATE2='2023-04-27' ,@REPMODE=1,@SUMMARY=4,@BRAND_CHECK   = 1,
--@SIZE_CHECK   = 0
IF(@REPORTTYPE <> 'CUS')
	SET @DATE1 = (SELECT dbo.fn_GetStartDate(@DATE2,@REPORTTYPE))
 
SET @REPCRITERIA = '@As On Dated : ' + FORMAT(@DATE2, 'MM-dd-yyyy') +' Report Type: '+@REPORTTYPE 
IF @REPORTTYPE ='MTD'
SET @REPORTNAME = 'ECO-SKU-BRAND-MTD';
IF @REPORTTYPE ='YTD'
SET @REPORTNAME = 'ECO-SKU-BRAND-YTD';
IF @REPORTTYPE ='QTD'
SET @REPORTNAME = 'ECO-SKU-BRAND-QTD';
IF @REPORTTYPE ='CUS'
SET @REPORTNAME = 'ECO-SKU-BRAND-CUSTOM';


IF (@SUMMARY IN (0,4))
 BEGIN


if OBJECT_ID('tempdb..#DATA') is not null drop table #DATA
if OBJECT_ID('tempdb..#MAIN') is not null drop table #MAIN
if OBJECT_ID('tempdb..#RESULT') is not null drop table #RESULT 
if OBJECT_ID('tempdb..#RESULT2') is not null drop table #RESULT2
--
--
IF OBJECT_ID('TEMPDB..#VCHR') is not null drop table #VCHR
	CREATE TABLE #VCHR (VNO VARCHAR(30))

	INSERT INTO #VCHR
	SELECT VCHRNO FROM TRNMAIN A WITH (NOLOCK) 
	WHERE
	A.VoucherType = 'TI'
	AND	(@STOCKIESTNAME = '%' OR ( @STOCKIESTNAME <> '%' AND A.COMPANYID  IN (SELECT * FROM DBO.SPLIT(@STOCKIESTNAME,','))))
	AND	(@SALESMANID = '%' OR (@SALESMANID <> '%' AND A.SALESMANID  IN (SELECT * FROM DBO.SPLIT(@SALESMANID,','))))
	AND	(@BEAT = '%' OR ( @BEAT <> '%' AND A.RouteCode  IN (SELECT * FROM DBO.SPLIT(@BEAT,','))))
	 
	EXCEPT
	SELECT DISTINCT ISNULL(REFBILL,'') FROM TRNMAIN WITH (NOLOCK)
	WHERE VOUCHERTYPE <> 'TI'


SELECT A.TRNDATE,A.PARAC,GRA.DRCP ,MI.MCODE MMCODE ,MI.DESCA,MI.MCAT,IIF(@SUMMARY=0 OR @BRAND_CHECK=1,BRAND_MANUAL,'') BRAND_MANUAL    ,IIF(@SUMMARY=0 OR @SIZE_CHECK=1,SIZE_MANUAL,'') SIZE_MANUAL  ,G.RouteName [BEAT_NAME],F.NAME SALESMAN,C.ACNAME STOCKIESTNAME ,A.COMPANYID STOCKIESTID,B.MCODE  INTO #MAIN   FROM
 #VCHR X 
 JOIN	TRNPROD B  WITH (NOLOCK)  ON X.VNO=B.VCHRNO
 JOIN  TRNMAIN  A  WITH (NOLOCK)  ON A.VCHRNO= B.VCHRNO  
 JOIN (SELECT DISTINCT MCODE,CATEGORYCODE,DESCA,MCAT,BRAND_MANUAL,SIZE_MANUAL FROM MENUITEM) MI ON MI.MCODE=B.MCODE 
 LEFT JOIN 
		ROUTE_MASTER G WITH (NOLOCK) ON A.ROUTECODE=G.ROUTECODE
		LEFT JOIN SALESMAN F WITH (NOLOCK) ON A.SALESMANID=F.SSMCODE 
		LEFT JOIN RMD_ACLIST C WITH (NOLOCK) ON A.COMPANYID =C.customerID
		LEFT JOIN 
		(SELECT DISTINCT SSMCODE, COUNT(DISTINCT ACID)DRCP FROM RMD_ACLIST GROUP BY SSMCODE) GRA ON GRA.SSMCODE=isnull(F.SSMCODE,'~')
		WHERE  
		(@MCODE = '%' OR ( @MCODE <> '%' AND B.MCODE IN (SELECT * FROM DBO.SPLIT(@MCODE,',')))) 
		AND(@MCAT = '%' OR ( @MCAT <> '%' AND MI.MCAT IN (SELECT * FROM DBO.SPLIT(@MCAT,','))))   
		AND(@BRAND = '%' OR ( @BRAND <> '%' AND MI.BRAND_MANUAL  IN (SELECT * FROM DBO.SPLIT(@BRAND,','))))	
	
		--DIVISION IS FOR FOOD (MCAT)

 
	 
 ---JOIN FOR DIFFERENT WISE
  
	  
SELECT  MATERIALCODE,	EC.BEAT_NAME,	EC.SALESMAN,	EC.STOCKIESTNAME,EC.BRAND_MANUAL,EC.SIZE_MANUAL, MATERIALNAME, MCAT,	EC.ECO_LY	,EC.ECO_LM	,EC.ECO_CM 	,
	COALESCE(OLSSM.DRCP,OLBEAT.DRCP,OLSTK.DRCP)DRCP,
	COALESCE(OLSSM.OUTLET_LY,OLBEAT.OUTLET_LY,OLSTK.OUTLET_LY)OUTLET_LY,
	COALESCE(OLSSM.OUTLET_LM,OLBEAT.OUTLET_LM,OLSTK.OUTLET_LM)	OUTLET_LM,
	COALESCE(OLSSM.OUTLET_CM,OLBEAT.OUTLET_CM,OLSTK.OUTLET_CM)	OUTLET_CM 	 INTO #RESULT		FROM (
   select   
IIF(@SUMMARY=4,'',MCODE)  MATERIALCODE ,IIF(@SUMMARY=4,'',DESCA) MATERIALNAME , IIF(@REPMODE=0 ,BEAT_NAME,'')BEAT_NAME,IIF(@REPMODE<=1 ,SALESMAN,'')SALESMAN, IIF(@REPMODE <=2 ,STOCKIESTNAME,'')STOCKIESTNAME,
  BRAND_MANUAL, SIZE_MANUAL, 
MCAT,
		COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL))  AS ECO_LY , 
		COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL)) AS ECO_LM,
		COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	AS ECO_CM
		 
	from #MAIN 
	GROUP BY   iif(@SUMMARY=4,'',MCODE), iif(@SUMMARY=4,'',DESCA) ,mcat, IIF(@REPMODE=0 ,BEAT_NAME,''),
	 IIF(@REPMODE<=1 ,SALESMAN,''),
	 IIF(@REPMODE <=2 ,STOCKIESTNAME,'') ,BRAND_MANUAL,SIZE_MANUAL
  ) EC
  LEFT join
  (SELECT SALESMAN  ,DRCP ,
  COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL))  AS OUTLET_LY , 
		COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL)) AS OUTLET_LM,
		COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	AS OUTLET_CM
		FROM #MAIN GROUP BY SALESMAN ,DRCP ) OLSSM
		ON 
		OLSSM.SALESMAN=ec.SALESMAN AND @REPMODE=1

	LEFT join
	( SELECT BEAT_NAME ,DRCP,COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL))  AS OUTLET_LY , 
		COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL)) AS OUTLET_LM,
		COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	AS OUTLET_CM
		FROM #MAIN group by BEAT_NAME,DRCP  )OLBEAT
		ON
	OLBEAT.BEAT_NAME=ec.BEAT_NAME AND @REPMODE=0

	LEFT join
	( 
 select A.STOCKIESTNAME ,B.DRCP,OUTLET_LY,OUTLET_LM,OUTLET_CM from(
	SELECT STOCKIESTNAME  ,STOCKIESTID ,COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL))  AS OUTLET_LY , 
		COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL)) AS OUTLET_LM,
		COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	AS OUTLET_CM
		FROM #MAIN group by STOCKIESTID,STOCKIESTNAME  
		)A LEFT join
		(
	SELECT B.COMPANYID,COUNT(DISTINCT ACID) DRCP FROM RMD_ACLIST A JOIN SALESMAN B ON A.SSMCODE = B.SSMCODE GROUP BY B.COMPANYID
   )B
		ON B.COMPANYID=A.STOCKIESTID
		
		) OLSTK
		ON
		 OLSTK.STOCKIESTNAME=ec.STOCKIESTNAME AND @REPMODE=2

   
SELECT   MATERIALCODE,	BEAT_NAME,  MATERIALNAME , BRAND_MANUAL, SIZE_MANUAL,MCAT DIVISION,	SALESMAN,	STOCKIESTNAME,	ECO_LY	,ECO_LM	,ECO_CM	,DRCP,	OUTLET_LY,	OUTLET_LM,	OUTLET_CM  ,CASE WHEN OUTLET_LY=0 THEN 0 ELSE (CAST (ECO_LY AS float)*100)  /OUTLET_LY  END [ECO%LY],
		  	CASE WHEN OUTLET_LM=0 THEN 0 ELSE (CAST (ECO_LM AS float)/OUTLET_LM) *100  END [ECO%LM], 	CASE WHEN OUTLET_CM=0 THEN 0 ELSE (CAST (ECO_CM AS float) /OUTLET_CM)*100    END [ECO%CM]
		  INTO
		  #RESULT2 FROM #RESULT A  
   
 
 
 --RESULT QUERY
 SELECT   MATERIALCODE	,MATERIALNAME,	NULLIF(BRAND_MANUAL,	'ZZZZZZZZZZ')BRAND_MANUAL,NULLIF (SIZE_MANUAL,'ZZZZZZZZZZ')SIZE_MANUAL,DIVISION	,BEAT_NAME,	SALESMAN	,STOCKIESTNAME,	DRCP	,ECO_LY	,ECO_LM,	ECO_CM,	OUTLET_LY,	OUTLET_LM	,OUTLET_CM	,[ECO%LY] 	,[ECO%LM],	[ECO%CM],	FLG,	FFLG  FROM (
 SELECT   MATERIALCODE,  	MATERIALNAME, BRAND_MANUAL, SIZE_MANUAL,  DIVISION,
		 BEAT_NAME,
		 SALESMAN	,
		 STOCKIESTNAME,
		 DRCP,
		 ECO_LY	,
		 ECO_LM	,
		 ECO_CM, 
		 OUTLET_LY,	
		 OUTLET_LM,
		 OUTLET_CM	,
		 format([ECO%LY],'n2') [ECO%LY],
		 format([ECO%LM],'n2') [ECO%LM],
		 format([ECO%CM],'n2')[ECO%CM],
		 'A'FLG ,'R'FFLG
 FROM #RESULT2 

 UNION ALL

 SELECT  'TOTAL' MATERIALCODE,''  MATERIALNAME,  'ZZZZZZZZZZ' BRAND_MANUAL,
	   'ZZZZZZZZZZ'SIZE_MANUAL	 ,NULL DIVISION,
		 IIF(@REPMODE=0,BEAT_NAME,NULL)BEAT,
		 IIF(@REPMODE=1,SALESMAN,NULL)SALESMAN,
		 IIF(@REPMODE=2,STOCKIESTNAME,NULL)STOCKEISTNAME,
		 NULL DRCP,
		 COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL)) AS ECO_LY ,
			COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL))AS ECO_LM,
			COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	 AS ECO_CM,
		 NULL OUTLET_LY ,
		 NULL OUTLET_LM,
		 NULL OUTLET_CM,
		 NULL [ECO%LY],
		 NULL [ECO%LM],
		 NULL [ECO%CM],
		 'C'FLG ,'B'FFLG
		 FROM #MAIN GROUP BY IIF(@REPMODE=0,BEAT_NAME,NULL),IIF(@REPMODE=1,SALESMAN,NULL),IIF(@REPMODE=2,STOCKIESTNAME,NULL)
  
  UNION ALL
  
  SELECT 
	 NULL MATERIALCODE	,
	 NULL MATERIALNAME	,
	  BRAND_MANUAL,
	 SIZE_MANUAL	,
	 NULL DIVISION	,
	 IIF(@REPMODE=0,BEAT_NAME,NULL)BEAT,
	 IIF(@REPMODE=1,SALESMAN,NULL)SALESMAN,
	 IIF(@REPMODE=2,STOCKIESTNAME,NULL)STOCKEISTNAME, 
	 NULL DRCP,
		 COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL)) AS ECO_LY ,
			COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL))AS ECO_LM,
			COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	 AS ECO_CM,
		 NULL OUTLET_LY ,
		 NULL OUTLET_LM,
		 NULL OUTLET_CM,
		 NULL [ECO%LY],
		 NULL [ECO%LM],
		 NULL [ECO%CM],
		 'B'FLG ,'B'FFLG 
		 FROM #MAIN A 
		  WHERE @SUMMARY <> 4
		  GROUP BY BRAND_MANUAL ,SIZE_MANUAL,IIF(@REPMODE=0,BEAT_NAME,NULL),IIF(@REPMODE=1,SALESMAN,NULL),IIF(@REPMODE=2,STOCKIESTNAME,NULL)


  )SUUM
  ORDER BY CASE @REPMODE WHEN 0 THEN BEAT_NAME WHEN 1 THEN SALESMAN  WHEN 2 THEN STOCKIESTNAME END ,  SUUM.BRAND_MANUAL  ,   SUUM.SIZE_MANUAL  ,FLG


SELECT NULL

END

ELSE
BEGIN

IF OBJECT_ID('tempdb..#DATA2') is not null drop table #DATA2
IF OBJECT_ID('tempdb..#MAIN2') is not null drop table #MAIN2
IF OBJECT_ID('tempdb..#RESULTX') is not null drop table #RESULTX 
IF OBJECT_ID('tempdb..#RESULT2X') is not null drop table #RESULT2X

IF OBJECT_ID('TEMPDB..#VCHR2') is not null drop table #VCHR2
	CREATE TABLE #VCHR2 (VNO VARCHAR(30))

	INSERT INTO #VCHR2
	SELECT VCHRNO FROM TRNMAIN A WITH (NOLOCK) 
	WHERE
	A.VoucherType = 'TI'
	AND	(@STOCKIESTNAME = '%' OR ( @STOCKIESTNAME <> '%' AND A.COMPANYID  IN (SELECT * FROM DBO.SPLIT(@STOCKIESTNAME,','))))
	AND	(@SALESMANID = '%' OR (@SALESMANID <> '%' AND A.SALESMANID  IN (SELECT * FROM DBO.SPLIT(@SALESMANID,','))))
	AND	(@BEAT = '%' OR ( @BEAT <> '%' AND A.RouteCode  IN (SELECT * FROM DBO.SPLIT(@BEAT,','))))
	EXCEPT
	SELECT DISTINCT ISNULL(REFBILL,'') FROM TRNMAIN WITH (NOLOCK)
	WHERE VOUCHERTYPE <> 'TI'


SELECT A.TRNDATE,A.PARAC ,MI.MCODE MMCODE ,MI.BRAND_MANUAL,MI.SIZE_MANUAL,MI.DESCA,MI.MCAT ,G.RouteName [BEAT_NAME],F.NAME SALESMAN,C.ACNAME STOCKIESTNAME ,B.COMPANYID STOCKIESTID,B.MCODE INTO #MAIN2 
FROM  
 #VCHR2 X 
JOIN TRNPROD B  ON B.VCHRNO=X.VNO JOIN (SELECT DISTINCT VCHRNO,PARAC,TRNDATE,SALESMANID,ROUTECODE,COMPANYID,VoucherType FROM TRNMAIN )A ON A.VCHRNO= B.VCHRNO AND B.VOUCHERTYPE='TI'
JOIN (SELECT DISTINCT MCODE,CATEGORYCODE,DESCA,MCAT,BRAND_MANUAL,SIZE_MANUAL FROM MENUITEM) MI ON MI.MCODE=B.MCODE 
 LEFT JOIN 
		ROUTE_MASTER G WITH (NOLOCK) ON A.ROUTECODE=G.ROUTECODE
		LEFT JOIN SALESMAN F WITH (NOLOCK) ON A.SALESMANID=F.SSMCODE 
		LEFT JOIN RMD_ACLIST C WITH (NOLOCK) ON A.COMPANYID =C.customerID
		LEFT JOIN 
		(SELECT DISTINCT SSMCODE, COUNT(DISTINCT ACID)DRCP FROM RMD_ACLIST GROUP BY SSMCODE) GRA ON GRA.SSMCODE=F.SSMCODE
		WHERE 
		(@MCODE = '%' OR ( @MCODE <> '%' AND B.MCODE IN (SELECT * FROM DBO.SPLIT(@MCODE,',')))) 
		AND(@MCAT = '%' OR ( @MCAT <> '%' AND MI.MCAT IN (SELECT * FROM DBO.SPLIT(@MCAT,','))))   
		AND(@BRAND = '%' OR ( @BRAND <> '%' AND MI.BRAND_MANUAL  IN (SELECT * FROM DBO.SPLIT(@BRAND,','))))	


 
   

 SELECT    	EC.BRAND_MANUAL, EC.SIZE_MANUAL,	EC.MCAT,EC.SALESMAN,	EC.ECO_LY	,EC.ECO_LM	,EC.ECO_CM 	 , 
	COALESCE(OLBR.OUTLET_LY,OLSZ.OUTLET_LY,OLSSM.OUTLET_LY)OUTLET_LY,
	COALESCE(OLBR.OUTLET_LM,OLSZ.OUTLET_LM,OLSSM.OUTLET_LM)	OUTLET_LM,
	COALESCE(OLBR.OUTLET_CM,OLSZ.OUTLET_CM,OLSSM.OUTLET_CM)	OUTLET_CM 
	
	INTO #RESULTX		FROM 
		(
select     MCAT,IIF(@SUMMARY=1 ,BRAND_MANUAL,'')BRAND_MANUAL,IIF(@SUMMARY=2 ,SIZE_MANUAL,'')SIZE_MANUAL, IIF(@SUMMARY  =3 ,SALESMAN,'')SALESMAN,
		--START OF ECO_LY
			COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL)) AS ECO_LY ,
			COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL))AS ECO_LM,
			COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	 AS ECO_CM

	 
	from  #MAIN2
    GROUP BY MCAT,IIF(@SUMMARY=1 ,BRAND_MANUAL,''),
	 IIF(@SUMMARY=2 ,SIZE_MANUAL,''),
	 IIF(@SUMMARY=3 ,SALESMAN,'') 

	 )EC
	 
LEFT join
 (
 SELECT BRAND_MANUAL  , 
	COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL)) AS OUTLET_LY,
	COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL)) AS OUTLET_LM,
	COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL)) AS OUTLET_CM

	FROM #MAIN2  group by BRAND_MANUAL   ) OLBR
	on
	OLBR.BRAND_MANUAL=ec.BRAND_MANUAL AND @SUMMARY=1
 
 LEFT join
 (
 SELECT SIZE_MANUAL , 
	COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL)) AS OUTLET_LY,
	COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL)) AS OUTLET_LM,
	COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	 AS OUTLET_CM

	 FROM #MAIN2  group by SIZE_MANUAL   ) OLSZ
	 on
	 OLSZ.SIZE_MANUAL=ec.SIZE_MANUAL AND @SUMMARY=2

 LEFT join
 (
 SELECT SALESMAN  ,
	COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL)) AS OUTLET_LY,
	COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL)) AS OUTLET_LM,
	COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))AS OUTLET_CM

	 FROM #MAIN2  group by SALESMAN) OLSSM
	 on
	 OLSSM.SALESMAN=ec.SALESMAN AND @SUMMARY=3
 
  
  ---ADDING ECO 
  
 SELECT    BRAND_MANUAL ,  SIZE_MANUAL,SALESMAN, MCAT DIVISIONS  ,	ECO_LY	,ECO_LM	,ECO_CM	  ,	OUTLET_LY,	OUTLET_LM,	OUTLET_CM  ,CASE WHEN OUTLET_LY=0 THEN 0 ELSE (CAST (ECO_LY AS float)*100)  /OUTLET_LY  END [ECO%LY],
		  	CASE WHEN OUTLET_LM=0 THEN 0 ELSE (CAST (ECO_LM AS float)/OUTLET_LM) *100  END [ECO%LM], 	CASE WHEN OUTLET_CM=0 THEN 0 ELSE (CAST (ECO_CM AS float) /OUTLET_CM)*100    END [ECO%CM]
		  INTO
		  #RESULT2X FROM #RESULTX A 

		    


		   --RESULT QUERY

		    SELECT  NULL MATERIALCODE	,NULL MATERIALNAME, BRAND_MANUAL	,SIZE_MANUAL, 	SALESMAN, NULL BEAT_NAME,NULL STOCKIESTNAME
,	 DIVISIONS DIVISION,  DRCP,ECO_LY	,ECO_LM,	ECO_CM,	OUTLET_LY,	OUTLET_LM	,OUTLET_CM	,
			[ECO%LY] 	,[ECO%LM],	[ECO%CM],	FLG,	FFLG  
			FROM (
					
					SELECT   BRAND_MANUAL,  	SIZE_MANUAL,SALESMAN,   DIVISIONS,DRCP,
		 ECO_LY	,
		 ECO_LM	,
		 ECO_CM, 
		 OUTLET_LY,	
		 OUTLET_LM,
		 OUTLET_CM	,
		 format([ECO%LY],'n2') [ECO%LY],
		 format([ECO%LM],'n2') [ECO%LM],
		 format([ECO%CM],'n2')[ECO%CM],
		 'A'FLG ,'R'FFLG
 FROM #RESULT2X RX
 
 CROSS APPLY (SELECT COUNT(DISTINCT ACID) DRCP FROM RMD_ACLIST WHERE ISNULL(SSMCODE,'') <>'')B 
 
 union all

 SELECT   'Total' BRAND_MANUAL, NULL SIZE_MANUAL, NULL SALESMAN,   MCAT   DIVISIONS, NULL DRCP,
	 
	COUNT( DISTINCT IIF( TRNDATE BETWEEN DATEADD(year, -1, @DATE1) AND DATEADD(year, -1, @DATE2) ,PARAC, NULL)) AS ECO_LY ,
			COUNT( DISTINCT IIF(TRNDATE  BETWEEN DATEADD (MM,-1, @DATE1) AND DATEADD (MM,-1, @DATE2),PARAC,NULL))AS ECO_LM,
			COUNT(DISTINCT IIF(TRNDATE  BETWEEN @DATE1 AND @DATE2,PARAC,NULL))	 AS ECO_CM,
		 NULL OUTLET_LY ,
		 NULL OUTLET_LM,
		 NULL OUTLET_CM,
		 NULL [ECO%LY],
		 NULL [ECO%LM],
		 NULL [ECO%CM],
		 'B'FLG ,'B'FFLG
 FROM #MAIN2  GROUP BY MCAT 
 )SUUM
  ORDER BY DIVISIONS, FLG,CASE @SUMMARY WHEN 1 THEN BRAND_MANUAL WHEN 2 THEN SIZE_MANUAL  WHEN 3 THEN SALESMAN END    

  SELECT NULL
 
 END

  
 
 