 

CREATE or ALTER   PROCEDURE [dbo].[WSP_StockSettlement] 
--DECLARE
	@DATE1 DATE,
	@DATE2 DATE,
	@DIVISION VARCHAR(3)= '%',
	@FYID VARCHAR(10) = '%'
AS
--select @DATE1='2022-01-01' ,@DATE2='2023-01-01' ,@FYID='79/80'
DECLARE @COLQTY NVARCHAR(MAX)
 SET @colQty = STUFF((SELECT distinct ',' + QUOTENAME(TRNMODE ) +' varchar (max),'+ QUOTENAME(TRNMODE+' Value' ) +' varchar(max)'
            FROM INVMAIN WHERE VOUCHERTYPE = 'DM' FOR XML PATH(''), TYPE  ).value('.', 'NVARCHAR(MAX)')  ,1,1,'') 
 
		 
DECLARE @QUERY NVARCHAR(MAX)

set @QUERY='DECLARE @RESULT TABLE(MENUCODE VARCHAR(100),	DESCA VARCHAR(MAX), 	BASEUNIT VARCHAR(100) ,	Opening	VARCHAR(200) ,Purchase		VARCHAR(200) ,[Transfer In]	VARCHAR(200) ,	[Transfer Out]	VARCHAR(200) ,	[MCODE] 	VARCHAR(200) ,' + @COLQTY +
', SETTLEMENTVALUE	 VARCHAR(200) ,SALESCOST  VARCHAR(200) ,	STOCKADJUSTMENTVALUE VARCHAR(200) ,	STOCKBALANCE VARCHAR(200) ,	STOCKVALUE VARCHAR(200)) 

INSERT INTO @RESULT
EXEC RSP_StockSettlement @DATE1=' + ''''+FORMAT (@DATE1,'dd/MM/yyyy') + ''''+', @DATE2= ' + ''''+FORMAT (@DATE2,'dd/MM/yyyy') + ''''+ ', @DIVISION='+ ''''+@DIVISION + ''''+',@FYID='+ ''''+@FYID+ ''''+'
SELECT * ,COUNT(*) OVER() ALLCOUNT FROM @RESULT 
'

 
 EXEC SP_EXECUTESQL @QUERY;
  