--USE [BBSM_CENTRAL]
--GO
--/****** Object:  StoredProcedure [dbo].[WSP_DISPATCH_REPORTSBL]    Script Date: 06/27/2023 5:00:49 PM ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO

ALTER   PROCEDURE [dbo].[WSP_DISPATCH_REPORTSBL]
--DECLARE
@DATE1 DATETIME,
@DATE2 DATETIME,
@SALESMANID VARCHAR(100)='%',--AGENT
@CUSTOMERACID VARCHAR(100)='%',
@MODE TINYINT =1,--MODE 1 FOR DISPATCH ONLY ,MODE 0 FOR ALL
@SUMMARY tinyint= 1 --0 FOR DETAIL , 1 FOR SUMMARY
AS
--SELECT @DATE1='2022-05-04',@DATE2='2023-05-22',@MODE=0,@SUMMARY=0
 
  
 

   select LC.VOUCHERNO DISPATCHVOUCHER ,DM.MITI DISPATCH_MITI,SSM.NAME AGENT,OM.VCHRNO ORDERNO,LID.MCODE,LID.ITEMDESC ,LID.MRP,LID.QUANTITY,OM.BSDATE ORDERMITI,TM.VCHRNO INVOICENO,TM.TRNAC,TM.BSDATE INVOICEMITI,LC.TRNDATE DISPATCHDATE,TP.WAREHOUSE GODOWN ,RA.ACNAME ,COUNT(*) OVER() ALLCOUNT from TRNMAIN TM    LEFT join LOADCHARTVOUCHERDETAIL LD ON  TM.VCHRNO=LD.REFBILL  
    LEFT JOIN LOADCHARTITEMDETAIL LID ON LD.VOUCHERNO=LID.VOUCHERNO AND @summary=0

	 JOIN
	 (SELECT DISTINCT VCHRNO , WAREHOUSE FROM TRNPROD) TP ON TP.VCHRNO=TM.VCHRNO
	 LEFT JOIN
	 SALESMAN SSM ON SSM.SALESMANID=TM.SALESMANID
	LEFT JOIN  
	(SELECT DISTINCT REFBILL ,BSDATE,VCHRNO FROM RMD_ORDERMAIN WHERE VCHRNO LIKE 'SO%')OM ON OM.VCHRNO=TM.REFORDBILL
	 LEFT JOIN
	 (SELECT DISTINCT VOUCHERNO, CONVERT(DATE,[DATE]) TRNDATE FROM LOADCHART) LC ON LC.VOUCHERNO=LD.VOUCHERNO
	 LEFT JOIN
	 (SELECT DISTINCT ACID , ACNAME FROM RMD_ACLIST WHERE ACID LIKE 'PA%') RA ON RA.ACID=TM.TRNAC
	 LEFT JOIN
	 DATEMITI DM
	 ON  DM.AD=LC.TRNDATE
	 WHERE TM.TRNDATE BETWEEN @DATE1 AND @DATE2
	 AND ISNULL(TM.SALESMANID,'') LIKE @SALESMANID
	 and ((@mode=0) or(@mode=1 and LC.VOUCHERNO is not null))
  