CREATE OR ALTER   PROCEDURE  [dbo].[WSP_STOCKSETTLEMNTSTATUS]
--DECLARE
	@DATE1 DATETIME,
	@DATE2 DATETIME,
	@SETTLEMENTMODE VARCHAR(25) = '%',
	@DIVISION VARCHAR(15) = '%',
	@WAREHOUSE VARCHAR(25) = '%',
	@MGROUP VARCHAR(25),
	@FYID VARCHAR(10) = ''
AS 

DECLARE @RESULT TABLE (MENUCODE	 VARCHAR(300),DESCA	VARCHAR(1000),BASEUNIT	VARCHAR(300),OPQTY	NUMERIC(32,2),REALQTY_IN	NUMERIC(32,2),REALQTY		NUMERIC(32,2),NETQTY		NUMERIC(32,2),PRATE_A NUMERIC(32,2),AMOUNT	NUMERIC(32,2),mcode VARCHAR(300) )

--SELECT  @DATE1='2023-04-01 00:00:00',@DATE2='2023-06-22 00:00:00',@SETTLEMENTMODE=N'%',@DIVISION=N'%',@WAREHOUSE=N'%',@MGROUP=N'%',@FYID=N'79/80'

INSERT INTO @RESULT
exec RSP_STOCKSETTLEMNTSTATUS 
@DATE1=@DATE1,
@DATE2=@DATE2,
@SETTLEMENTMODE=@SETTLEMENTMODE,
@DIVISION=@DIVISION,
@WAREHOUSE=@WAREHOUSE,
@MGROUP=@MGROUP,
@FYID=@FYID


SELECT *,COUNT(*) OVER() ALLCOUNT , 'TOTAL' MENUCODE ,  SUM(OPQTY) OVER() OPQTY,SUM(REALQTY_IN) OVER() REALQTY_IN,SUM(REALQTY) OVER() REALQTY,SUM(NETQTY ) OVER() NETQTY ,SUM(AMOUNT) OVER() AMOUNT
FROM @RESULT

 