CREATE OR ALTER   VIEW [dbo].[RMD_TRNTRAN_CREDITORS]
AS
SELECT VCHRNO,DIVISION,A_ACID,DRAMNT,CRAMNT,CHEQUEDATE,A.COSTCENTER,A.COMPANYID,NULL REFVNO 
FROM RMD_TRNTRAN A  WITH (NOLOCK) INNER JOIN RMD_ACLIST B WITH (NOLOCK)  ON A.A_ACID = B.ACID 
WHERE B.PTYPE = 'V' AND A_ACID LIKE 'PA%' AND ((VCHRNO NOT LIKE 'AO%' AND CRAMNT >0) OR (VCHRNO LIKE 'AO%' AND CRAMNT >0)) 
AND VCHRNO NOT IN (SELECT DISTINCT VCHRNO FROM PARTYOPENING_DETAIL WITH (NOLOCK) )
UNION ALL
SELECT VCHRNO,DIVISION,A.ACID,0 DRAMNT,AMOUNT CRAMNT,a.REFDATE,NULL,A.COMPANYID,A.REFVNO 
FROM PARTYOPENING_DETAIL A WITH (NOLOCK)  INNER JOIN RMD_ACLIST B WITH (NOLOCK)  ON A.ACID = B.ACID AND B.PTYPE = 'V'
GO


