 --CREATE OR ALTER PROC WSP_ASSETS_COMPANY_NORMS

DECLARE 
@PHISCALID VARCHAR(25)='%',
@MODE TINYINT =1  --1 : DEPRECIATION POOLWISE || 2 DEPN ACCOUNT HEADWISE || 3 DEPN ITEMWISE || 4 DEPN ASSETID WISE
--AS
 SELECT @PHISCALID='80/81',@MODE=1
IF OBJECT_ID('tempdb..#DATA') is not null drop table #DATA
	/*
	SELECT AG.GROUPNAME [POOL],DP.AssetID ,DP.BOOKVALUE,DP.ORIGNALCOST,DP.MON,DP.DEPRECIATION_VALUE ,DP.PHISCALID ,AD.MON ASSETMON,DP.NETBOOKVALUE,RA.ACNAME ACCOUNTHEADING ,DP.ACID,ASM.MENUCODE ASSETCODE,ASM.DESCA ASSET_NAME,ASM.DESCRIPTION DESCRIPTIONS,BMA.BATCHCREATEDATE PURCHASEDATE
	INTO #DATA 
	FROM DEPRECIATION DP WITH (NOLOCK)
	LEFT JOIN ASSET_GROUP_LEDGER AGL WITH (NOLOCK) ON AGL.ACID=DP.ACID
	LEFT JOIN ASSET_GROUP AG WITH (NOLOCK) ON AG.ASSETGROUPID=  AGL.ASSETGROUPID
	LEFT JOIN ASSETCODE_MASTER AM  WITH (NOLOCK) ON AM.MCODE=DP.MCODE AND AM.ASSETID=DP.ASSETID  
	LEFT JOIN ASSETCODE_DETAIL AD  WITH (NOLOCK) ON AM.ASSETID= AD.ASSETID AND AM.BATCHCODE=AD.BATCHCODE
	LEFT JOIN RMD_ACLIST RA WITH (NOLOCK) ON RA.ACID=DP.ACID
	LEFT JOIN ASSET_MENUITEM ASM WITH (NOLOCK) ON ASM.MCODE=DP.MCODE
	LEFT JOIN BATCHPRICE_MASTER_ASSET BMA WITH (NOLOCK) ON BMA.BATCHCODE=DP.BATCHCODE
	WHERE DP.PHISCALID=@PHISCALID
	*/
	SELECT ''[CLASS CODE],ASM.MENUCODE ASSETCODE,BMA.BATCHCREATEDATE PURCHASEDATE,ASM.DESCA ASSETNAME,AM.ASSETID,ASM.DESCRIPTION DESCRIPTIONS,RA.ACNAME SUPPLIERNAME,''  [LOCATION]
 
	,1 QTY ,AD.MON MON ,BMA.COSTPRICE ,DP.DEPRECIATION_VALUE,DP.DEP_PHISCALID ,AD.PHISCALID ASSET_PHISCALID FROM ASSETCODE_MASTER AM  WITH (NOLOCK) 
	LEFT JOIN ASSETCODE_DETAIL AD  WITH (NOLOCK) ON AM.ASSETID= AD.ASSETID AND AM.BATCHCODE=AD.BATCHCODE
	LEFT JOIN BATCHPRICE_MASTER_ASSET BMA WITH (NOLOCK) ON BMA.BATCHCODE=AM.BATCHCODE AND BMA.MCODE= AM.MCODE
	LEFT JOIN ASSET_MENUITEM ASM WITH (NOLOCK) ON ASM.MCODE=AM.MCODE
	LEFT JOIN RMD_ACLIST RA WITH (NOLOCK) ON RA.ACID=ASM.SUPCODE
	LEFT JOIN (	 SELECT ASSETID,MCODE,BATCHCODE ,SUM(DEPRECIATION_VALUE)DEPRECIATION_VALUE,PHISCALID DEP_PHISCALID FROM DEPRECIATION  WITH (NOLOCK) GROUP BY  ASSETID,MCODE,BATCHCODE,PHISCALID) DP ON DP.MCODE=AM.MCODE AND DP.BATCHCODE=AM.BATCHCODE
	 
	  
	 
	  