CREATE OR ALTER PROC WSP_ASSETS_COMPANY_NORMS
	--DECLARE 
	@POOL VARCHAR(25) = '%', --POOL (ASSET_GROUP)
	@ITEM VARCHAR(50) = '%', --ASSET CODE (ASSET MENUITEM MCODE)
	@BLOCK VARCHAR(50) = '%', --BLOCK (RMD_ACLIST)
	@PHISCALID VARCHAR(25) = '%',
	@ASSETID VARCHAR(100) = '%', --ASSET ID(ASSET MASTER)
	@MODE TINYINT = 1 --1 : FARR POOLWISE || 2 FARR ACCOUNT HEADWISE || 3 FARR ITEMWISE || 4 FARR ASSETID WISE
AS
--SELECT @PHISCALID='80/81',@MODE=2,@HEADING='%'
IF OBJECT_ID('tempdb..#DATA') IS NOT NULL
	DROP TABLE #DATA

DECLARE @DATE DATETIME

SELECT @DATE = (
		SELECT ENDDATE
		FROM PhiscalYear
		WHERE PhiscalID = @PHISCALID
		)

SELECT '' [CLASS CODE],
	ASM.MENUCODE ASSETCODE,
	BMA.BATCHCREATEDATE PURCHASEDATE,
	ASM.DESCA ASSETNAME,
	AM.ASSETID,
	ASM.DESCRIPTION DESCRIPTIONS,
	RA.ACNAME SUPPLIERNAME,
	'' [LOCATION],
	AM.ACID,
	1 QTY,
	AD.MON MON,
	BMA.COSTPRICE,
	DP.DEPRECIATION_FY,
	DP.DEPRECIATION_BFY,
	AD.PHISCALID ASSET_PHISCALID,
	DEPDATE,
	AG.GroupName [POOLNAME],
	RAC.ACNAME HEADING,
	AGL.AssetGroupID
INTO #DATA
FROM ASSETCODE_MASTER AM WITH (NOLOCK)
LEFT JOIN ASSETCODE_DETAIL AD WITH (NOLOCK) ON AM.ASSETID = AD.ASSETID
	AND AM.BATCHCODE = AD.BATCHCODE
LEFT JOIN BATCHPRICE_MASTER_ASSET BMA WITH (NOLOCK) ON BMA.BATCHCODE = AM.BATCHCODE
	AND BMA.MCODE = AM.MCODE
LEFT JOIN ASSET_MENUITEM ASM WITH (NOLOCK) ON ASM.MCODE = AM.MCODE
LEFT JOIN RMD_ACLIST RA WITH (NOLOCK) ON RA.ACID = ASM.SUPCODE
LEFT JOIN (
	SELECT ASSETID,
		MCODE,
		BATCHCODE,
		SUM(CASE 
				WHEN PHISCALID = @PHISCALID
					THEN DEPRECIATION_VALUE
				ELSE 0
				END) DEPRECIATION_FY,
		SUM(CASE 
				WHEN PHISCALID <> @PHISCALID
					THEN DEPRECIATION_VALUE
				ELSE 0
				END) DEPRECIATION_BFY,
		trn_date DEPDATE
	FROM DEPRECIATION WITH (NOLOCK)
	WHERE isnull(trn_date, '1900-01-01') < @DATE
	GROUP BY ASSETID,
		MCODE,
		BATCHCODE,
		trn_date
	) DP ON DP.MCODE = AM.MCODE
	AND DP.BATCHCODE = AM.BATCHCODE
LEFT JOIN ASSET_GROUP_LEDGER AGL WITH (NOLOCK) ON AGL.ACID = AM.ACID
LEFT JOIN ASSET_GROUP AG WITH (NOLOCK) ON AG.ASSETGROUPID = AGL.ASSETGROUPID
LEFT JOIN RMD_ACLIST RAC WITH (NOLOCK) ON RAC.ACID = AM.ACID
WHERE ISNULL(BMA.BATCHCREATEDATE, '1900-01-01') < @DATE
	AND AGL.ASSETGROUPID LIKE @POOL
	AND AM.MCODE LIKE @ITEM
	AND AM.ACID LIKE @BLOCK
	AND AM.ASSETID LIKE @ASSETID

IF @MODE = 1
BEGIN
	SELECT POOLNAME,
		SUM(CASE 
				WHEN MON = 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ORIGNAL],
		SUM(CASE 
				WHEN MON <> 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ADDITION],
		SUM(COSTPRICE) [COST VALUE~ TOTAL],
		SUM(DEPRECIATION_BFY) [DEPRECIATION~OPENING],
		SUM(DEPRECIATION_FY) [DEPRECIATION~PERIODIC],
		SUM(DEPRECIATION_BFY + DEPRECIATION_FY) [DEPRECIATION~ACCUMULATED],
		SUM(COSTPRICE - DEPRECIATION_BFY - DEPRECIATION_FY) NETBOOKVALUE
	FROM #DATA
	GROUP BY POOLNAME
	ORDER BY POOLNAME
END

IF @MODE = 2
BEGIN
	SELECT ACID AC_CODE,
		POOLNAME,
		HEADING,
		SUM(CASE 
				WHEN MON = 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ORIGNAL],
		SUM(CASE 
				WHEN MON <> 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ADDITION],
		SUM(COSTPRICE) [COST VALUE~ TOTAL],
		SUM(DEPRECIATION_BFY) [DEPRECIATION~OPENING],
		SUM(DEPRECIATION_FY) [DEPRECIATION~PERIODIC],
		SUM(DEPRECIATION_BFY + DEPRECIATION_FY) [DEPRECIATION~ACCUMULATED],
		SUM(COSTPRICE - DEPRECIATION_BFY - DEPRECIATION_FY) NETBOOKVALUE
	FROM #DATA
	GROUP BY ACID,
		POOLNAME,
		HEADING
	ORDER BY POOLNAME
END

IF @MODE = 3
BEGIN
	SELECT POOLNAME,
		HEADING,
		ASSETNAME,
		DESCRIPTIONS,
		SUM(CASE 
				WHEN ASSET_PHISCALID <> @PHISCALID
					THEN QTY
				ELSE 0
				END) [QUANTITY~OP],
		SUM(CASE 
				WHEN ASSET_PHISCALID = @PHISCALID
					THEN QTY
				ELSE 0
				END) [QUANTITY~IN],
		SUM(QTY) [QUANTITY~NET],
		SUM(CASE 
				WHEN MON = 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ORIGNAL],
		SUM(CASE 
				WHEN MON <> 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ADDITION],
		SUM(COSTPRICE) [COST VALUE~ TOTAL],
		SUM(DEPRECIATION_BFY) [DEPRECIATION~OPENING],
		SUM(DEPRECIATION_FY) [DEPRECIATION~PERIODIC],
		SUM(DEPRECIATION_BFY + DEPRECIATION_FY) [DEPRECIATION~ACCUMULATED],
		SUM(COSTPRICE - DEPRECIATION_BFY - DEPRECIATION_FY) NETBOOKVALUE
	FROM #DATA
	GROUP BY POOLNAME,
		HEADING,
		ASSETNAME,
		DESCRIPTIONS
	ORDER BY POOLNAME
END

IF @MODE = 4
BEGIN
	SELECT POOLNAME,
		HEADING,
		ASSETCODE,
		ASSETNAME,
		PURCHASEDATE,
		DESCRIPTIONS,
		SUPPLIERNAME,
		SUM(CASE 
				WHEN ASSET_PHISCALID <> @PHISCALID
					THEN QTY
				ELSE 0
				END) [QUANTITY~OP],
		SUM(CASE 
				WHEN ASSET_PHISCALID = @PHISCALID
					THEN QTY
				ELSE 0
				END) [QUANTITY~IN],
		SUM(QTY) [QUANTITY~NET],
		SUM(CASE 
				WHEN MON = 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ORIGNAL],
		SUM(CASE 
				WHEN MON <> 0
					THEN COSTPRICE
				ELSE 0
				END) [COST VALUE~ ADDITION],
		SUM(COSTPRICE) [COST VALUE~ TOTAL],
		SUM(DEPRECIATION_BFY) [DEPRECIATION~OPENING],
		SUM(DEPRECIATION_FY) [DEPRECIATION~PERIODIC],
		SUM(DEPRECIATION_BFY + DEPRECIATION_FY) [DEPRECIATION~ACCUMULATED],
		SUM(COSTPRICE - DEPRECIATION_BFY - DEPRECIATION_FY) NETBOOKVALUE
	FROM #DATA
	GROUP BY POOLNAME,
		HEADING,
		ASSETNAME,
		DESCRIPTIONS,
		ASSETCODE,
		PURCHASEDATE,
		SUPPLIERNAME
	ORDER BY POOLNAME
END

SELECT NULL