CREATE OR ALTER PROCEDURE WSP_ReceipeConsumptionReport
--DECLARE
@DATE1 DATE,
@DATE2 DATE,
@DIVISION VARCHAR(3) = '%',
@MCODE VARCHAR(25) = '%',
@SELECTEDITEMLIST VARCHAR(500) = ''

AS


--SET @DATE1='2024-01-01 00:00:00'; SET @DATE2='2024-01-03 00:00:00'; SET @DIVISION=N'%'; SET @MCODE=N'%'; SET @SELECTEDITEMLIST=N'%'
 
IF OBJECT_ID('tempdb..#DATA') IS NOT NULL 
    DROP TABLE #DATA;
 

CREATE TABLE #DATA ( 
MCODE VARCHAR(MAX),	MENUCODE VARCHAR(MAX),	DESCA VARCHAR(MAX),	CONSUMEDUNIT VARCHAR(MAX),	CONSUMEDQTY NUMERIC (32,2),	CONRATIOQTY NUMERIC (32,2),	SOLDQTY NUMERIC (32,2),
CONSUMEDAMOUNT NUMERIC (32,2),	CONRATIOAMOUNT NUMERIC (32,2) ,	FLG VARCHAR(MAX),	[TYPE] VARCHAR(MAX))
 
 

INSERT INTO #DATA
EXEC RSP_RECEIPECONSUMPTIONREPORT @DATE1=@DATE1,   @DATE2=@DATE2,   @DIVISION=@DIVISION,  @MCODE=@MCODE,   @SELECTEDITEMLIST=@SELECTEDITEMLIST


SELECT *,COUNT(*) OVER () ALLCOUNT  FROM #DATA